AGENT_TOOL_SCOPES: dict[str, list[str]] = {
    "pm": [
        "confluence_search",
        "confluence_get_page",
        "confluence_create_page",
        "confluence_update_page",
        "confluence_add_comment",
    ],
    "architecture": [
        "confluence_get_page",
        "confluence_create_page",
        "confluence_add_label",
        "get_me",
        "create_repository",
        "push_files",
        "create_or_update_file",
        "get_file_contents",
    ],
    "jira_structuring": [
        "confluence_get_page",
        "confluence_get_page_children",
        "confluence_create_page",
        "confluence_add_label",
        "jira_list_projects",
        "jira_get_project",
        "jira_get_field_options",
        "jira_create_issue",
        "jira_update_issue",
        "jira_add_comment",
        "jira_get_issue_link_types",
    ],
    "planning": [
        "confluence_get_page",
        "jira_get_issue",
        "get_file_contents",
        "list_branches",
        "issue_write",
        "assign_copilot_to_issue",
        "get_copilot_job_status",
    ],
    "qa": [
        "jira_get_issue",
        "pull_request_read",
        "add_issue_comment",
        "assign_copilot_to_issue",
    ],
    "review": [
        "confluence_get_page",
        "jira_get_issue",
        "pull_request_read",
        "pull_request_review_write",
        "merge_pull_request",
        "request_copilot_review",
    ],
    "jira_update": [
        "jira_get_transitions",
        "jira_transition_issue",
        "jira_add_comment",
        "pull_request_read",
    ],
}
